CREATE DATABASE QLNH
GO
USE QLNH
GO


CREATE TABLE KHACHHANG
(
    CMND VARCHAR(20),
	TenKH NVARCHAR(30),
	NgaySinh DATE,
	GioiTinh BIT, 
	DiaChi NVARCHAR(50),
	SoDienThoai VARCHAR(10), 

	CONSTRAINT PK_KHACHHANG PRIMARY KEY(CMND)
)
GO


CREATE TABLE TAIKHOAN
(
    SoTK VARCHAR(20),
	TenTK NVARCHAR(30) UNIQUE NOT NULL,
	MatKhau VARCHAR(20),
	NgayDangKy DATE DEFAULT GETDATE(),
	SoThe VARCHAR(20),
	SoDu BIGINT DEFAULT 0,
	CMND VARCHAR(20) NOT NULL,

	CONSTRAINT PK_TAIKHOAN PRIMARY KEY(SoTK),
	CONSTRAINT FK_TAIKHOAN FOREIGN KEY (CMND) REFERENCES dbo.KHACHHANG(CMND)
)
GO


CREATE TABLE GIAODICH
(
	MaGD VARCHAR(20),
	LoaiGD NVARCHAR(20),
	NgayGD DATE DEFAULT GETDATE() NOT NULL,


	CONSTRAINT PK_GIAODICH PRIMARY KEY(MaGD),
	
)
GO

CREATE TABLE CHITIETGD
(
	STT INT IDENTITY,
	MaGD VARCHAR(20),
	SoTK VARCHAR(20),
	SoTKNhan VARCHAR(20),
	SoTien BIGINT,
	NoiDungGD NVARCHAR(50)

	CONSTRAINT PK_CHITIETGD PRIMARY KEY(MaGD, SoTK)
	CONSTRAINT FK_GIAODICH_SoTKNhan FOREIGN KEY (SoTKNhan) REFERENCES TAIKHOAN(SoTK)
)
GO 



ALTER TABLE CHITIETGD ADD FOREIGN KEY(MaGD) REFERENCES GIAODICH(MaGD)
ALTER TABLE CHITIETGD ADD FOREIGN KEY(SoTK) REFERENCES TAIKHOAN(SoTK)



INSERT  INTO KHACHHANG(CMND, TenKH, NgaySinh, GioiTinh, DiaChi, SoDienThoai)
VALUES(2804, N'Hoàng Long', '2001-03-03', 1, N'Quận 9', 0909)


INSERT INTO TAIKHOAN(SoTK, TenTK, MatKhau, NgayDangKy, SoThe, SoDu, CMND)
VALUES(123, N'hoanglong', '03032001', '2020-05-22', 321, 0, 2804)

INSERT INTO GIAODICH(MaGD, LoaiGD)
VALUES(1, N'Nạp Tiền')

INSERT INTO CHITIETGD(MaGD, SoTK, SoTien, NoiDungGD)
VALUES(1, 123, 10000000, N'Nạp tý cho vui')

